/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.comercialcarlosbenjamin.vista;

/**
 *
 * @author Notebook
 */
public class MenuPrincipalGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName());

    /**
     * Creates new form MenuPrincipalGUI
     */
    public MenuPrincipalGUI() {
        initComponents();
    }
    public javax.swing.JPanel getPanelPrincipal() {
        return panelPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        itemInicio = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemAgregarUsuario = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        itemAgregarProducto = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        itemVender = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        panelPrincipal.setLayout(new java.awt.CardLayout());

        menuInicio.setText("Inicio");

        itemInicio.setText("Ir a Inicio");
        menuInicio.add(itemInicio);

        jMenuBar.add(menuInicio);

        menuUsuarios.setText("Usuarios");

        itemAgregarUsuario.setText("Agregar Nuevo Usuario");
        menuUsuarios.add(itemAgregarUsuario);

        jMenuBar.add(menuUsuarios);

        menuProductos.setText("Productos");

        itemAgregarProducto.setText("Agregar Producto");
        itemAgregarProducto.setToolTipText("");
        menuProductos.add(itemAgregarProducto);

        jMenuBar.add(menuProductos);

        menuVentas.setText("Ventas");

        itemVender.setText("Vender");
        menuVentas.add(itemVender);

        jMenuBar.add(menuVentas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem itemAgregarProducto;
    public javax.swing.JMenuItem itemAgregarUsuario;
    public javax.swing.JMenuItem itemInicio;
    public javax.swing.JMenuItem itemVender;
    public javax.swing.JMenuBar jMenuBar;
    public javax.swing.JMenu menuInicio;
    public javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuUsuarios;
    public javax.swing.JMenu menuVentas;
    public javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
